namespace DinnerTable;
public static class Seed {
 private static readonly List<Ingredient> BaseIngredients = [
 new("beef","Lean ground beef (90/10)","Protein","g",454,4.98m),new("turkey","Ground turkey (93/7)","Protein","g",454,3.48m),new("pork","Boneless pork loin","Protein","g",1361,8.94m),new("rice","Long-grain rice","Grains & pantry","g",907,1.88m),new("pasta","Pasta","Grains & pantry","g",454,0.98m),new("tortilla","Flour tortillas","Grains & pantry","each",10,1.98m),new("beans","Black beans, drained","Canned goods","g",255,0.86m),new("tomato","Diced tomatoes","Canned goods","g",411,0.96m),new("chickpea","Chickpeas, drained","Canned goods","g",255,0.86m),new("lentil","Dry lentils","Grains & pantry","g",454,1.48m),new("chicken","Boneless chicken thighs","Protein","g",1361,8.97m),new("egg","Eggs","Protein","each",12,3.24m),new("cheese","Shredded cheddar","Dairy","g",226,1.97m),new("onion","Yellow onions","Produce","g",1361,2.48m),new("potato","Potatoes","Produce","g",2268,3.47m),new("carrot","Carrots","Produce","g",454,0.98m),new("veg","Frozen mixed vegetables","Frozen","g",340,0.98m),new("corn","Frozen corn","Frozen","g",340,0.98m),new("oil","Cooking oil","Grains & pantry","ml",473,2.48m),new("spice","All-purpose seasoning","Grains & pantry","g",85,1.18m),new("soy","Soy sauce","Grains & pantry","ml",444,1.58m)
 ];
 public static readonly List<Ingredient> Ingredients = BaseIngredients.Concat(SeedExpansion.ExtraIngredients).ToList();
 public static List<Recipe> Recipes => SeedExpansion.Build(BaseRecipes);
 private static Recipe R(string id,string name,string desc,string category,int minutes,Portion[] p,params string[] steps)=>new(id,name,desc,category,minutes,4,p.ToList(),steps);
 private static Portion P(string id,decimal q)=>new(id,q);
 private static readonly List<Recipe> BaseRecipes = [
  R("turkey-chili","Hearty turkey & bean chili","A generous helping of turkey, beans and rich tomato.","Protein focused",35,[P("turkey",700),P("beans",510),P("tomato",822),P("onion",150),P("rice",240),P("oil",15),P("spice",12)],"Cook rice according to the package.","Brown ground turkey and diced onion in oil. Stir in seasoning, drained beans and tomatoes.","Simmer 20 minutes, adding water as needed. Ensure turkey reaches 165°F / 74°C. Serve over rice."),
 R("beef-pasta","Beef & tomato pasta skillet","Meaty tomato sauce and pasta, finished with cheddar.","Protein focused",30,[P("beef",650),P("pasta",350),P("tomato",822),P("onion",150),P("cheese",100),P("spice",8)],"Cook pasta according to its package.","Brown beef and diced onion in a skillet until beef reaches 160°F / 71°C. Drain excess fat.","Add tomatoes and seasoning; simmer 10 minutes. Stir in pasta and top with cheese."),
 R("pork-potatoes","Roasted pork loin & potatoes","Tender sliced pork with golden potatoes and carrots.","Protein focused",50,[P("pork",700),P("potato",800),P("carrot",300),P("oil",25),P("spice",10)],"Heat oven to 425°F / 220°C. Dice potatoes and carrots, toss with half the oil and seasoning, and roast 15 minutes.","Rub pork with remaining oil and seasoning and add to the pan. Roast until the center reaches 145°F / 63°C, about 25–35 minutes depending on thickness.","Rest pork for at least 3 minutes before slicing. Continue roasting vegetables if needed until tender."),
 R("chicken-fried-rice","Chicken & egg fried rice","Plenty of chicken, fluffy egg and colorful vegetables.","Protein focused",30,[P("chicken",650),P("rice",300),P("egg",4),P("veg",340),P("soy",40),P("oil",20)],"Cook rice following the package instructions.","Dice chicken and stir-fry in oil until it reaches 165°F / 74°C. Add vegetables and heat through.","Push to the side, add eggs and scramble until set. Stir in rice and soy sauce and cook until steaming hot."),
 R("bean-bowls","Smoky black bean bowls","Warm rice, seasoned beans & sweet corn.","Plant forward",25,[P("rice",300),P("beans",510),P("corn",170),P("onion",150),P("oil",15),P("spice",8)],"Cook rice according to package directions.","Dice onion and soften in oil. Add drained beans, corn and seasoning; simmer with a splash of water for 8 minutes.","Serve the bean mixture over rice."),
 R("chicken-rice","One-pan chicken & rice","A comforting classic with almost no cleanup.","One pan",35,[P("chicken",600),P("rice",300),P("carrot",200),P("onion",150),P("oil",15),P("spice",8)],"Season chicken; brown in oil in a deep skillet.","Add diced onion and carrots, rice and water as directed on the rice package. Cover and simmer until rice is tender.","Check chicken reaches 165°F / 74°C; add water and continue cooking if needed."),
 R("tomato-pasta","Rustic tomato & lentil pasta","A hearty, budget-friendly weeknight staple.","Plant forward",35,[P("pasta",400),P("lentil",160),P("tomato",822),P("onion",150),P("oil",15),P("spice",8)],"Simmer lentils in water until tender, about 20–25 minutes; drain.","Soften diced onion in oil. Add tomatoes and seasoning; simmer 10 minutes.","Cook pasta according to its package. Toss with lentils and sauce."),
 R("fried-rice","Golden egg fried rice","Colorful vegetables, soft egg & savory rice.","Quick dinner",20,[P("rice",300),P("egg",6),P("veg",340),P("soy",40),P("oil",20)],"Cook rice according to package instructions.","Heat oil in a wide pan and cook vegetables until hot throughout. Push to one side and scramble eggs until set.","Add rice and soy sauce. Stir-fry until steaming hot."),
 R("quesadilla","Black bean quesadillas","Crisp tortillas with a melty, hearty filling.","Family favorite",20,[P("tortilla",8),P("beans",510),P("cheese",180),P("corn",170),P("spice",6)],"Warm drained beans and corn with seasoning; lightly mash.","Divide filling and cheese between tortillas and fold.","Toast in a dry skillet over medium heat until golden and the cheese melts."),
 R("tray-chicken","Sheet-pan chicken & potatoes","Golden potatoes, sweet carrots & tender chicken.","One pan",45,[P("chicken",650),P("potato",800),P("carrot",250),P("onion",150),P("oil",25),P("spice",10)],"Heat oven to 425°F / 220°C. Cut potatoes and carrots into small even pieces.","Toss vegetables and chicken with oil and seasoning on a large sheet pan.","Roast 30–40 minutes, turning vegetables halfway. Check chicken reaches 165°F / 74°C."),
 R("chickpea-stew","Cozy chickpea & tomato stew","A rich pantry dinner spooned over fluffy rice.","Plant forward",30,[P("chickpea",510),P("tomato",411),P("rice",300),P("onion",150),P("carrot",150),P("oil",15),P("spice",8)],"Cook rice according to its package.","Soften chopped onion and carrots in oil. Stir in seasoning, tomatoes and drained chickpeas.","Add a little water and simmer 15 minutes. Serve over rice."),
 R("loaded-potato","Loaded bean & cheese potatoes","Fluffy baked potatoes with all the good stuff.","Family favorite",60,[P("potato",1000),P("beans",510),P("cheese",150),P("corn",170),P("spice",6)],"Scrub and pierce potatoes. Bake at 425°F / 220°C until tender, about 40–60 minutes, or microwave until soft.","Heat beans, corn and seasoning with a splash of water.","Split potatoes and top with bean mixture and cheese."),
 R("lentil-soup","Country lentil soup","An easy pot of vegetables, lentils & comfort.","Plant forward",35,[P("lentil",300),P("carrot",250),P("potato",400),P("onion",150),P("tomato",411),P("oil",15),P("spice",10)],"Soften diced onion and carrots in oil.","Add rinsed lentils, diced potatoes, tomatoes, seasoning and enough water to cover generously.","Simmer 25–30 minutes until lentils and potatoes are tender; adjust water and seasoning."),
 R("chicken-tacos","Skillet chicken tacos","Seasoned chicken & beans in warm tortillas.","Family favorite",25,[P("chicken",450),P("beans",255),P("tortilla",8),P("cheese",100),P("onion",150),P("oil",15),P("spice",8)],"Dice chicken and onion; sauté in oil with seasoning until chicken reaches 165°F / 74°C.","Add drained beans and heat through.","Warm tortillas and fill with chicken, beans and cheese.")
 ];
}
