using DinnerTable;
using Microsoft.AspNetCore.Builder;
var builder=WebApplication.CreateBuilder();
builder.Environment.ContentRootPath=Path.Combine(Path.GetTempPath(),"DinnerTable-tests-"+Guid.NewGuid());
var db=new Store(builder.Environment);var engine=new MealEngine(db);var s=db.Read();int count=0;
void Check(bool condition,string name){if(!condition)throw new Exception(name);Console.WriteLine("PASS "+name);count++;}
ActionRequest A(string type,int? people=null,int? nights=null,decimal? budget=null,string id=null,int? index=null)=>new(type,people,nights,budget,id,index);
engine.Apply(s,A("generate"));Check(s.Meals.Count==5,"requested dinner count");Check(s.Meals.Distinct().Count()==5,"variety without repeated dinners");
Check(s.Meals.Count(id=>db.Recipes.Single(r=>r.Id==id).HasMeat)>=4,"at least four meat dinners in five-night plan");
Check(s.Meals.All(id=>db.Recipes.Single(r=>r.Id==id).ProteinPerServing>=30),"every dinner meets protein target");
var original=engine.Grocery(s);Check(original.Select(g=>g.Id).Distinct().Count()==original.Count,"duplicate ingredients consolidated");Check(original.Sum(x=>x.Cost)<=s.Budget,"default plan within budget");
engine.Apply(s,A("settings",people:8));var doubled=engine.Grocery(s);Check(doubled.All(x=>x.Quantity==original.Single(g=>g.Id==x.Id).Quantity*2),"serving quantities double");Check(doubled.All(x=>x.Packs*x.PackSize>=x.Quantity),"whole packages cover ingredient needs");
var old=s.Meals[0];engine.Apply(s,A("swap",index:0));Check(s.Meals[0]!=old&&s.Meals.Count==5,"swap changes one dinner");Check(s.Meals.Count(id=>db.Recipes.Single(r=>r.Id==id).HasMeat)>=4&&s.Meals.All(id=>db.Recipes.Single(r=>r.Id==id).ProteinPerServing>=30),"swaps preserve meat and protein rules");engine.Apply(s,A("remove",index:0));Check(s.Meals.Count==4,"remove recalculates plan");
engine.Apply(s,A("favorite",id:old));engine.Apply(s,A("dislike",id:s.Meals[0]));var excluded=s.Meals[0];engine.Apply(s,A("generate",people:4,budget:1));Check(!s.Meals.Contains(excluded),"dislikes excluded from generation");Check(engine.Grocery(s).Sum(x=>x.Cost)>s.Budget,"impossible budget remains visibly over budget");
engine.Apply(s,A("check",id:engine.Grocery(s)[0].Id));db.Save(s,true);var reopened=new Store(builder.Environment);var restored=reopened.Read();Check(restored.People==s.People&&restored.Budget==s.Budget&&restored.Meals.SequenceEqual(s.Meals)&&restored.Favorites.SetEquals(s.Favorites)&&restored.Dislikes.SetEquals(s.Dislikes)&&restored.Checked.SetEquals(s.Checked),"SQLite survives store restart with all preferences");Check(reopened.History().Length==1,"history snapshot persisted");
try{engine.Apply(s,A("generate",people:0));throw new Exception("invalid accepted");}catch(ArgumentException){Check(true,"invalid input rejected");}
foreach(var r in db.Recipes)if(!s.Dislikes.Contains(r.Id))engine.Apply(s,A("dislike",id:r.Id));try{engine.Apply(s,A("generate"));throw new Exception("all dislikes accepted");}catch(ArgumentException){Check(true,"all-disliked collection handled");}
var sparse=new PlanState{Nights=7,Dislikes=db.Recipes.Where(r=>r.Id!="chicken-fried-rice").Select(r=>r.Id).ToHashSet()};engine.Apply(sparse,A("generate"));Check(sparse.Meals.Count==7&&sparse.Meals.All(id=>id=="chicken-fried-rice"),"sparse collection repeats eligible meat instead of silently dropping preferences");
Check(restored.MinProteinPerServing==30&&restored.MeatDinnerFraction==.94m,"protein preferences survive restart");
Check(db.Recipes.Count==50&&db.Recipes.Count(r=>r.HasMeat)==47&&db.Recipes.Count(r=>!r.HasMeat)==3,"catalog has exactly 47 meat and 3 meatless dinners");
Check(db.Recipes.Select(r=>r.Id).Distinct().Count()==50&&db.Recipes.All(r=>r.Ingredients.All(p=>db.Ingredients.Any(i=>i.Id==p.IngredientId))&&r.ProteinPerServing>=30),"all recipe ingredients resolve and all recipes meet protein target");
var week=new PlanState{WeekStart="2026-09-21"};CalendarPlan.SetMeal(week,"2026-09-23","bean-bowls",db.Recipes);CalendarPlan.SetMeal(week,"2026-09-21","chicken-rice",db.Recipes);Check(week.MealDates.SequenceEqual(new[]{"2026-09-21","2026-09-23"})&&week.Meals[1]=="bean-bowls","calendar permits an explicit meatless choice and sorts days");
try{CalendarPlan.SetMeal(week,"2026-09-28","chicken-rice",db.Recipes);throw new Exception("outside week accepted");}catch(ArgumentException){Check(true,"calendar rejects dates outside selected week");}
db.Save(week,false);var second=db.SwitchWeek("2026-09-30");Check(second.WeekStart=="2026-09-28"&&second.Meals.Count==0,"new week starts independently");CalendarPlan.SetMeal(second,"2026-09-29","beef-pasta",db.Recipes);db.Save(second,false);var firstAgain=db.SwitchWeek("2026-09-22");Check(firstAgain.Meals.SequenceEqual(week.Meals)&&firstAgain.MealDates.SequenceEqual(week.MealDates),"switching weeks restores original dated dinners");
var retailer=new WalmartAdapter(db);db.SaveDocument("walmart-settings",new RetailerSettings("99353","3261","Richland Supercenter"));var basket=retailer.BuildBasket(firstAgain,engine.Grocery(firstAgain));Check(basket.Unmatched==0&&basket.CartUrl!.StartsWith("https://www.walmart.com/sc/cart/addToCart?items=")&&basket.CartUrl.Contains("storeId=3261"),"Walmart cart URL contains matched products and selected store");Check(basket.Lines.All(l=>l.Quantity*l.Match!.PackageQuantity>=l.Ingredient.Quantity),"Walmart quantities cover the required ingredients");Check(!basket.CompletePricing&&basket.KnownSubtotal==0,"missing prices never masquerade as a complete quote");
Check(WalmartProducts.Seeds.Count==db.Ingredients.Count&&WalmartProducts.Seeds.All(m=>db.Ingredients.Any(i=>i.Id==m.IngredientId&&i.Unit==m.Unit)),"every ingredient has a unit-compatible suggested Walmart product");
try{WalmartAdapter.ValidateMatch(new("rice","bad&items=1","Bad",0,"g"),db.Ingredients);throw new Exception("bad match accepted");}catch(ArgumentException){Check(true,"invalid product IDs and package sizes rejected");}
var savedMatches=WalmartProducts.Seeds;savedMatches.RemoveAll(m=>m.IngredientId=="rice");db.SaveDocument("walmart-matches",savedMatches);var partial=retailer.BuildBasket(firstAgain,engine.Grocery(firstAgain));Check(partial.Unmatched==1&&partial.CartUrl==null,"unmatched ingredient prevents partial cart handoff");
var dated=new PlanState{WeekStart="2026-09-21",Nights=2};CalendarPlan.SetMeal(dated,"2026-09-23","chicken-rice",db.Recipes);CalendarPlan.SetMeal(dated,"2026-09-26","chicken-tacos",db.Recipes);engine.Apply(dated,A("generate"));Check(dated.MealDates.SequenceEqual(new[]{"2026-09-23","2026-09-26"}),"regeneration preserves selected nonconsecutive dinner dates");CalendarPlan.SetMeal(dated,"2026-09-27","chicken-rice",db.Recipes);Check(dated.Nights==3,"adding a calendar dinner expands requested night count");
Console.WriteLine($"{count} checks passed.");
